### ISSUE TITLE
Option to disable emoticon to emojis

### ISSUE THREAD

**Issue by acagastya** [convos-chat/convos#592]
Hi, I would like to request an option to disable the conversion of emoticons to emojis.  In the account section, we could have a checkbox which asks if we would like to convert, xor not.  If one does not wish to convert,  [this line](https://github.com/convos-chat/convos/blob/master/assets/store/I18N.js#L100) should be wrapped around a condition.

**Comment by jhthorsen** [comment]
It's not that simple, since `this.emojis.markup(str)` also handle unicode emojis.

Either way, the important question here is "why?" We can add endless of features, but we try our best to have good defaults, since checkboxes and other toggles makes the codebase harder to maintain, and the gui harder to understand.

**Comment by acagastya** [comment]
I understand the complexities involved, and things can get unnecessarily large adding all the features; however, when I type ":-D" and it converts to some emoji, that imo is additional feature.  I intended to type ":-D", I intended to see ":-D", but I would be getting emojis when I never intended to seeing those.  Besides, they appear different on different machines.

**Comment by jhthorsen** [comment]
>  Besides, they appear different on different machines.

No, they appear exactly the same, since the emojis are pictures.

I don't think I'm going to implement this myself, but I will consider a PR. What do you think @marcusramberg?

If someone starts working on this PR, then I think it should toggle more things. I think it should be a "Raw messages" and not "Emojis" toggle, since Emojis will be very confusing when some emojis are displayed anyways. "Raw messages" Could be rendered with:

- this._xmlEscape(str) - Disabling this will result in a security hole
- this._nbsp(str) - HTML does not support double spaces, so this must be enabled as well
- this._plainUrlToLink(str) - I think this is something everybody wants, but I could be wrong
- this.emojis.markup(str) - This can only be partially disabled, since unicode emojis must still be handled
- this._mdLink(str) - Markdown should be disabled
- this._mdCode(str) - Markdown should be disabled
- this._mdEmStrong(str) - Markdown should be disabled
- this._mdBlockQuote(str) - Markdown should be disabled

I'm also not sure if this should be a per message toggle or a global toggle.

**Comment by marcusramberg** [comment]
They still appear as :-D on non-convos clients right? But yeah, I agree a raw mode would be more generally useful, I think someone requested that in the chat yesterday too.
