### ISSUE TITLE
Chat input field sent messages/commands history

### ISSUE THREAD

**Issue by greenbigfrog** [convos-chat/convos#598]
Using the :arrow_up: key, puts the last message sent into the input field.

I send `Hello` in a channel, the input field is empty, I press the up arrow, it gets the last message sent in that channel and the input field contains `Hello` again.

I'd like this "buffer" to be per channel, although global would work as well.

**Comment by jberger** [comment]
do you mean this for things like chanserv commands? irc cannot edit a line like slack can

**Comment by greenbigfrog** [comment]
I know I can't edit, but I still like to be able to easily copy the last message. For posting somewhere else, for correcting myself, etc

**Comment by jhthorsen** [comment]
I think I want this to be global and not per channel.

**Comment by jhthorsen** [comment]
One issue with this is that since the input is a textarea, then up/down arrow can actually move up/down lines. Need to continue supporting that, but maybe this can work:

1. Empty input field allows going into history mode by pressing the up-arrow key.
2. Pressing arrow up/down one or many times will keep you in history mode.
3. You will only get out of history mode if the value does not match the current history element or if the cursor is *not* a the end of the line.
4. Changing the input value will reset the history index, and you have to clear the whole input to be able to get back into history mode.
