### ISSUE TITLE
Chat history support (IRCv3 draft standard)?

### ISSUE THREAD

**Issue by poVoq** [convos-chat/convos#605]
**Is your feature request related to a problem? Please describe.**
Even though Convos has a build-in bouncer, it would be nice if one could query older channel history before connecting via the new chat history IRCv3 draft standard: https://ircv3.net/specs/extensions/chathistory

KiwiIRC has support for that and it is working very nicely.

Thanks for considering this :)

**Comment by jhthorsen** [comment]
I think this issue will go into the [fridge](https://github.com/convos-chat/convos/milestone/20), since it's still a draft and Libera does not yet support it.

Libera is not the master of what goes into Convos or not, but it does help if it supports it.

<img width="223" alt="T1pCXX43dPwHCvXH" src="https://user-images.githubusercontent.com/45729/122493830-5301ed00-d023-11eb-83d7-bcb7743f77f8.png">

**Comment by jhthorsen** [comment]
As always: I don't mind a PR 👍

**Comment by poVoq** [comment]
Old Freenode / Libera.chat holding back IRC as a whole (same old story for years) 😓

**Comment by jhthorsen** [comment]
Closing this, but making a link to #444.
